### PR TITLE
Fix for creeper bug, small

### LINKED ISSUE #2: Creeper explosions do not count towards the progress bar
Applies to all types of creepers. Might apply to other mobs that are blown up by TNT too.

### PR DESCRIPTION
**Pull request by SekretOne**
### Fixed
1. Fix #2 (Creeper explosion not counting) 💥 
2. Fix small progress bar bug getting stuck client side

### Changed
1. Doc markdown to parse accurately with standard md readers
2. Invasion completion calc refactor to simpler logic
    
### Additions
1. Add test templates in `/test/resources` 
    
---

###  Other
1. Package Info
2. Add tests
    1. Now includes testing frameworks in gradle dep's

### CODE REVIEW

File: src/main/java/com/codetaylor/mc/onslaught/modules/onslaught/event/handler/InvasionKillCountUpdateEventHandler.java [hunk 1]
```diff
@@ -44,6 +43,41 @@ public void on(LivingDeathEvent event) {
...
+            .get(world),
+        entity
+            .getEntityData(),
+        world
+            .getMinecraftServer()
+            .getPlayerList()::getPlayerByUUID
+    );
+  }
+
+  public void on(Event event) {
```
Comment (democat3457) [inline src/main/java/com/codetaylor/mc/onslaught/modules/onslaught/event/handler/InvasionKillCountUpdateEventHandler.java]: Why is this extra `on` method necessary?

Comment (SekretOne) [reply src/main/java/com/codetaylor/mc/onslaught/modules/onslaught/event/handler/InvasionKillCountUpdateEventHandler.java]: Because I got distracted and left it dangling. Removed.

**Comment by SekretOne** [comment]
ty for the review. A few manual actions to actually tag and release, but it's all up: https://github.com/Rebirth-of-the-Night/onslaught/releases/tag/1.0.2
